Adding the Routing Indicator padding as described in the 3GPP TS 24.5…
aligungr/UERANSIM pull request #615
Opened 2023-03-17 09:48 UTC by Stg22

When the Routing Indicator is less than 4 digits, the value needs to be completed according to the table 9.11.3.4.1 in section 9.11.3.4 from the document 3GPP TS 24.501.

This patch proposes  a quick adaptation of encodeBCD.

2023-03-17 12:45 UTC, louisroyer requested changes
Typo in variable name: it should be `octetCount` and not `octectCount`.

2023-03-17 12:45 UTC, louisroyer commented on src/lib/nas/base.cpp
> +    size_t octectCount = 0;
```suggestion
    size_t octetCount = 0;
```

2023-03-17 12:45 UTC, louisroyer commented on src/lib/nas/base.cpp
> +        octectCount++;
```suggestion
        octetCount++;
```

2023-03-17 12:45 UTC, louisroyer commented on src/lib/nas/base.cpp
> +        while (octectCount < octetLength) {
```suggestion
        while (octetCount < octetLength) {
```

2023-03-17 12:45 UTC, louisroyer commented on src/lib/nas/base.cpp
> +            octectCount++;
```suggestion
            octetCount++;
```

2023-03-17 12:50 UTC, Stg22 commented
Sorry for the tipo on only so few modificated code :o(

2023-03-17 17:21 UTC, aligungr commented
Modifying `EncodeBcdString` function and accepting another parameter `bool isRoutingIndicator` would be confusing.
It's better to write a separate function to encode Routing Indicator, such as `EncodeRoutingIndicator`.
Could you fix this?

Thank you.

2023-03-20 08:29 UTC, Stg22 commented
Is it acceptable to modify EncodeBcdString to return the number of bytes pushed into the stream parameter? It will return size_t instead of void and the function EncodeRoutingIndicator could use EncodeBbdSting in easy way?

2023-03-20 14:21 UTC, closed without merging